### ISSUE TITLE
Add multiple external referral URL fields

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/external-referral-links#8]
Started from https://secure.helpscout.net/conversation/380919901/61043/?folderId=634609. 

There is only one available website URL field available at this time. It might be great to add multiple external URLs. 

"i have another question - i want to use the external links add on, as my sales pages are on another WP site. However, I have more than 1 sales page. When I downloaded the add-on, there is only space to enter one external URL. What do I do if I have multiple products and hence multiple sales pages?"

**Comment by gspice** [comment]
I could certainly be wrong, but I think she's asking one of two things:

1.  She's mistakenly installed the External Referral Links add-on on her main site where AffiliateWP and her eCommerce store resides (instead of installing it on the external WP sites where her sales pages are).

2. Or,  she's installed it on the external sites but thinks she has to list multiple pages to return to on her main site sales page, or somehow identify all individual sales pages. 

Just my two cents :-)

**Comment by sumobi** [comment]
Yeah, there's no need for multiple URL fields. You only need to specify one URL, and that "base" URL is your site where AffiliateWP resides. 

So all the customer needs to do is enter their base URL, If they link to multiple product pages on the site where AffiliateWP is installed, it will work fine.
